default:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  tags:
    - ord1-tenant

stages:
  - generate
  - build
  - release

variables:
  DOCKER_IMG: gateway
  FIXED_IMAGE_TAG: ${CI_COMMIT_SHORT_SHA}

build:image:
  stage: build
  variables:
    REF_IMAGE: $CI_REGISTRY_IMAGE/$DOCKER_IMG:$CI_COMMIT_REF_SLUG
    FIXED_IMAGE: $CI_REGISTRY_IMAGE/$DOCKER_IMG:$CI_COMMIT_SHORT_SHA
    DOCKERFILE: ${CI_PROJECT_DIR}/Dockerfile.coreweave
  before_script:
    - export HTTP_PROXY=${CACHE_PROXY}
    - export NO_PROXY=${CACHE_REGISTRY_HOST}
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script: |-
    /kaniko/executor \
      $KANIKO_ADDTL_ARGS \
      --context . \
      --dockerfile $DOCKERFILE \
      --destination $REF_IMAGE \
      --destination $FIXED_IMAGE

tag:release:
  stage: build
  image: node:lts-alpine3.15
  only:
    refs:
      - main
  artifacts:
    paths:
      - artifacts.env
    expire_in: 1 day
  before_script:
    - apk --no-cache add git
  script:
    - npm install
    - npx semantic-release

publish:release:
  stage: release
  only:
    refs:
      - main
  dependencies:
    - tag:release
  variables:
    IMAGE_NAME: ${DOCKER_IMG}
    REF_IMAGE: $CI_REGISTRY_IMAGE/$IMAGE_NAME:$CI_COMMIT_REF_SLUG
    FIXED_IMAGE: $CI_REGISTRY_IMAGE/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    DOCKERFILE: ${CI_PROJECT_DIR}/Dockerfile
  image:
    name: registry.gitlab.com/coreweave/utility-images/crane/debug:temp
    entrypoint: ["/busybox/sh"]
  before_script:
    - export $(cat artifacts.env | xargs)
  script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - crane tag "$CI_REGISTRY_IMAGE/$IMAGE_NAME:$CI_COMMIT_SHORT_SHA"  "$BUILD_VERSION"